argo(postgres): Allow to specify custom Sentry image

diff --git a/k8s/services/workflows/z-postgres.yaml b/k8s/services/workflows/z-postgres.yaml
--- a/k8s/services/workflows/z-postgres.yaml
+++ b/k8s/services/workflows/z-postgres.yaml
@@ -10,9 +10,17 @@ spec:
     strategy: OnWorkflowCompletion
   templates:
   - name: reset-and-run-migrations
+    inputs:
+      parameters:
+      - name: sentry_sha
+        value: default
     steps:
     - - name: reset-postgres
         template: reset-postgres
+        arguments:
+          parameters:
+          - name: sentry_sha
+            value: "{% raw %}{{inputs.parameters.sentry_sha}}{% endraw %}"
     - - name: run-migrations
         template: run-migrations
 
@@ -33,25 +41,39 @@ spec:
     serviceAccountName: default
 
   - name: run-migrations
+    inputs:
+      parameters:
+      - name: sentry_sha
+        value: default
     container:
       image: bitnami/kubectl:1.19
       command:
         - bash
         - -c
         - |
+          exec 2>&1
+          set -euo pipefail
 
-          SENTRY_IMAGE=$(kubectl get deployment -n default ingest-metrics-consumer -o jsonpath='{.spec.template.spec.containers[0].image}')
+          SENTRY_SHA='{% raw %}{{inputs.parameters.sentry_sha}}{% endraw %}'
+          if [[ "${SENTRY_SHA}" == "default" ]]; then
+            SENTRY_IMAGE=$(kubectl get deployment -n default ingest-metrics-consumer -o jsonpath='{.spec.template.spec.containers[0].image}')
+          else
+            SENTRY_IMAGE="getsentry/sentry:${SENTRY_SHA}"
+          fi
+
           if [[ "${SENTRY_IMAGE}" != *"getsentry/sentry"* ]]; then
             echo "Incorrect Sentry image: ${SENTRY_IMAGE}"
             exit 1
           fi
           echo "Using Sentry image: ${SENTRY_IMAGE}"
 
+          POD_NAME="run-migrations-{% raw %}{{workflow.uid}}{% endraw %}"
+
           cat <<EOF >/tmp/pod.yaml
           apiVersion: v1
           kind: Pod
           metadata:
-            name: "run-migrations-{% raw %}{{workflow.uid}}{% endraw %}"
+            name: "${POD_NAME}"
             namespace: "default"
             labels:
               workflowTemplate: 'run-migrations'
@@ -85,9 +107,26 @@ spec:
                   name: sentry-config
             restartPolicy: Never
           EOF
-
           kubectl apply -f /tmp/pod.yaml
 
+          echo 'Waiting for the migration to finish...'
+          while true; do
+            PHASE=$(kubectl get pod -n default "${POD_NAME}" -o jsonpath='{.status.phase}')
+            if [[ "${PHASE}" == "Succeeded" ]]; then
+              echo 'Done!'
+              exit 0
+            elif [[ "${PHASE}" == "Failed" ]]; then
+              echo 'Error!'
+              kubectl desribe pod -n default "${POD_NAME}"
+              exit 1
+            elif [[ ${PHASE} == "" ]]; then
+              echo 'Something went wrong.'
+              exit 1
+            else
+              echo "[$(date)] Waiting..."
+              sleep 5
+            fi
+          done
     serviceAccountName: default
   ttlStrategy:
     # 3 days
